version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: jegomez
      POSTGRES_PASSWORD: Kuroneco-1
      POSTGRES_DB: sip_db
    ports:
      - "5432:5432"

  web:
    image: web2py/web2py
    build: .
    ports: 
      - "8001:8000"
    command:  ["./entrypoint.sh"]
    depends_on:
      - db
    environment:
      WEB2PY_CONFIG: production
      POSTGRES_USER: jegomez
      POSTGRES_PASSWORD: Kuroneco-1
      POSTGRES_DB: sip_db
      APP_PASSWORD: root
